# Generated by Django 2.2 on 2020-09-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwatb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='项目详情')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.RemoveField(
            model_name='log',
            name='case_name',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.BooleanField(default=1, verbose_name='case状态，1：正常，0：删除'),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '执行中'), (1, '已通过'), (0, '未通过')], default=0, verbose_name='用例执行状态'),
        ),
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.CharField(default='{}', max_length=500, verbose_name='case详情'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=50, verbose_name='case名称'),
        ),
        migrations.AlterField(
            model_name='case',
            name='page_path',
            field=models.CharField(max_length=50, verbose_name='case对应的页面路径'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwatb.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwatb.Project', verbose_name='所属项目'),
        ),
    ]
